#this code was generated by ai

import numpy as np
import cv2
import random
import os

def generate_circle_edges(size=(256, 256), n_circles=3, min_r=10, max_r=50, noise=False):
    """
    Generate a binary image with circle edges (white pixels on black background).
    
    Args:
        size: (height, width)
        n_circles: number of circles
        min_r, max_r: radius range
        noise: add random white pixels to simulate noise
    Returns:
        img: binary edge image (uint8)
    """
    h, w = size
    img = np.zeros((h, w), np.uint8)

    for _ in range(n_circles):
        r = random.randint(min_r, max_r)
        cx = random.randint(r, w - r)
        cy = random.randint(r, h - r)
        cv2.circle(img, (cx, cy), r, 255, 1)  # thickness=1 → edge only

    if noise:
        n_noise = int(0.005 * h * w)
        coords = (np.random.randint(0, h, n_noise), np.random.randint(0, w, n_noise))
        img[coords] = 255

    return img

# Example usage
if __name__ == "__main__":
    os.makedirs("circle_edges_dataset", exist_ok=True)
    for i in range(10):
        img = generate_circle_edges(size=(256, 256),
                                    n_circles=3,
                                    noise=False)
        cv2.imwrite(f"circle_edges_dataset/circle_edges_{i:02d}.png", img)
